apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "environment.fullname" . }}-podinfo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.6.2
    helm:
      releaseName: podinfo
  destination:
    name: {{ .Release.Name }}
    namespace: default
  syncPolicy:
    automated: {}