apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "environment.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.20.0-beta.5
    helm:
      releaseName: {{ .Release.Name }}
      valuesObject:
        exportKubeConfig:
          server: https://{{ .Release.Name }}.{{ .Release.Name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Name }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true